import { Col, Row, Card } from 'antd'
import type { NextPage } from 'next'
import Head from 'next/head'
import ThemeSwitcher from '../components/ThemeSwitcher'
import styles from '../styles/Home.module.css'
import BookIcon from '../assets/icons/book.svg'
import CodeIcon from '../assets/icons/code.svg'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next DApp Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeSwitcher />
      <div className={styles.container}>
        <div className={styles.emptySpace} />
        <p className={styles.title}>DApp Starter</p>
        <Row>
          <Col xs={24} sm={24} md={12} lg={12} xl={12}>
            <Card className={styles.card}>
              <div className={styles.docTitle}>
                <BookIcon style={{width: '24px', marginRight: '8px'}} />
                <a href="https://nextjs.org/">
                  Next.js Docs
                </a>
              </div>
              <div>
                Next.js gives you the best developer experience with all the features you need for
                production: hybrid static &amp; server rendering, TypeScript support, smart
                bundling, route pre-fetching, and more. No config needed.
              </div>
            </Card>
          </Col>
          <Col xs={24} sm={24} md={12} lg={12} xl={12}>
            <Card className={styles.card}>
              <div className={styles.docTitle}>
                <BookIcon style={{width: '24px', marginRight: '8px'}} />
                <a href="https://wagmi.sh">
                  wagmi Docs
                </a>
              </div>
              <div>
                wagmi is a collection of React Hooks containing everything you need to start working
                with Ethereum. wagmi makes it easy to display ENS and balance information, sign
                messages, interact with contracts, and much more — all with caching, request
                deduplication, and persistence.
              </div>
            </Card>
          </Col>
          <Col xs={24} sm={24} md={12} lg={12} xl={12}>
            <Card className={styles.card}>
              <div className={styles.docTitle}>
                <BookIcon style={{width: '24px', marginRight: '8px'}} />
                <a href="https://ant.design">
                  Ant Design Docs
                </a>
              </div>
              <div>
                An enterprise-class UI design language and React UI library with a set of high-quality React components, one of best React UI library for enterprises.
              </div>
            </Card>
          </Col>
          <Col xs={24} sm={24} md={12} lg={12} xl={12}>
            <Card className={styles.card}>
              <div className={styles.docTitle}>
                <CodeIcon style={{width: '24px', marginRight: '8px'}} />
                About this Template
              </div>
              <div>
                This starter kit is composed of{' '}
                <a href="https://nextjs.org">
                  Next.js
                </a>{' '}
                and{' '}
                <a
                  href="https://ant.design"
                  className="underline"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ant Design
                </a>
                , with{' '}
                <a
                  href="https://docs.family.co/connectkit"
                  className="underline"
                  target="_blank"
                  rel="noreferrer"
                >
                  ConnectKit
                </a>
                ,{' '}
                <a href="https://ethers.org" className="underline" target="_blank" rel="noreferrer">
                  ethers
                </a>{' '}
                &amp;{' '}
                <a href="https://wagmi.sh" className="underline" target="_blank" rel="noreferrer">
                  wagmi
                </a>{' '}
                for all your web3 needs. It uses{' '}
                <a
                  href="https://www.typescriptlang.org/"
                  className="underline"
                  target="_blank"
                  rel="noreferrer"
                >
                  Typescript
                </a>{' '}
                and an opinionated directory structure for maximum dev confy-ness. Enjoy!
              </div>
            </Card>
          </Col>
        </Row>
      </div>
    </div>
  )
}

export default Home;
